[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
HOST = '0.0.0.0'
